### PR TITLE
Upgrade quickcheck and rawpointer

### PR DESCRIPTION
**Pull request by cuviper**

### CODE REVIEW

**Comment by bluss** [comment]
Thanks!

**Comment by cuviper** [comment]
I just realized that `odds` now duplicates `rawpointer`:

```
$ cargo tree -p odds
odds v0.4.0
├── rawpointer v0.2.1
├── rawslice v0.1.0
│   └── rawpointer v0.1.0
└── unchecked-index v0.2.2
```

Do you have any plan to release a new `rawslice`?

**Comment by bluss** [comment]
I'll try to do that. My favourite course of action would be to decommission odds at this point, and not have to maintain it. It must have showed up in someone's rdeps since it is getting attention.

**Comment by cuviper** [comment]
Hmm -- it showed up on my radar because Fedora packages it, but I don't see anything depending on it at this point, so we could just remove that.

In some of my personal code (for Project Euler), I'm using `odds::stride`, but maybe I should try that with `Iterator::step_by` these days.

**Pull request merged**
