### PR TITLE
Add a trait for checked indexing

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
I would like to bikeshed the name a bit, `checked_index` and `checked_index_mut` are quite long, I'd find shorter names preferable.

**Comment by bluss** [comment]
The usual name is get and get_mut, like slices do it. This was mentioned on irc today by @kimundi (not w.r.t arrayvec).

**Comment by tbu-** [comment]
These names are already taken though. Maybe `get_` and `get_mut_`?

**Comment by bluss** [comment]
Maybe checked index is good then. If we extend this to &str by the way, the has_index check needs to include character boundary checks (is_acceptable_index in odds).

I don't think has_index method should have any panicking case?

**Comment by tbu-** [comment]
`has_index` currently has the panicking case that `start > end`, but I consider that acceptable as that indicates a programmer error.

I have a small error there, it will currently panic if you use `start..` but it is out of range. In that case it panics.

It would need to include boundary checks for `&str`, yeah. Can we do that in a follow-up PR?

**Comment by tbu-** [comment]
Fixed the mistake.

Thanks for your fast response times by the way, it's wonderful!

**Comment by bluss** [comment]
Good catch.

I know I said I would easily accept this functionality, just imagined it as a simple function or so. I don't know.

I think there should be no possiblity of panic -- I use checked versions in places where you want to avoid panics, a possible panic in the optimizer's analysis may throw it off and miss some other optimizations.

**Comment by llogiq** [comment]
Why not `slice` and `slice_mut`?

**Comment by bluss** [comment]
It's going to cover both indexing and slicing, just like the Index trait.

**Comment by bluss** [comment]
Maybe we can use just something like this?

I'd like to not reuse the `Index` impls since we want a totally no-panic codepath anyway.

```rust
trait CheckedIndex<Idx> {
    type Output;
    fn get(&self) -> Option<&Self::Output>;
}
```

**Comment by bluss** [comment]
Optionally: Even add `len()` into the trait. That would put us close to a "Random Access (Iterator)" kind of interface.

**Comment by tbu-** [comment]
The optimizer has no problem with seeing the double bounds check, it will eliminate the panic anyway – I don't think not re-using `Index` is a good idea, as it just produces code duplication.

**Comment by bluss** [comment]
That's a good point, it's true most of the time.

**Comment by bluss** [comment]
I'm inclined to close this, since I don't agree with the approach. The crate space is free — it doesn't have to be in `odds` in particular.

**Comment by tbu-** [comment]
That's fine with me!

**Pull request closed without merging**
